# Generated by Django 4.0 on 2022-09-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri_sdm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebInfografis',
            fields=[
                ('idinfografis', models.IntegerField(db_column='IDInfografis', primary_key=True, serialize=False)),
                ('judul', models.CharField(blank=True, db_column='Judul', max_length=255, null=True)),
                ('tumbnail', models.ImageField(blank=True, db_column='Tumbnail', max_length=50, null=True, upload_to='media/infografis/thumbnails/')),
                ('lampiran', models.ImageField(blank=True, db_column='Lampiran', upload_to='media/infografis/images/')),
                ('keterangan', models.TextField(blank=True, db_column='Keterangan', null=True)),
                ('publish', models.BooleanField(blank=True, db_column='Publish', null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('createdby', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
            ],
            options={
                'db_table': 'Web_Infografis',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='infografis',
            table='Web_Infografis',
        ),
    ]
