# Generated by Django 4.0 on 2022-09-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri_sdm', '0002_webinfografis_alter_infografis_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, db_column='judul', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, db_column='thumbnail', null=True, upload_to='media/banner/thumbnails')),
                ('gambar', models.ImageField(db_column='gambar', upload_to='media/banner/images')),
                ('keterangan', models.TextField(blank=True, db_column='keterangan', null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('createdby', models.IntegerField(blank=True, db_column='CreateBy', null=True)),
            ],
            options={
                'db_table': 'Web_Banner',
            },
        ),
        migrations.DeleteModel(
            name='WebInfografis',
        ),
    ]
