# Generated by Django 4.0 on 2022-09-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenisAgenda', models.CharField(max_length=50)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Web_Agenda',
            },
        ),
    ]
