# Generated by Django 4.0 on 2022-09-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLengkap',
            fields=[
                ('idpegawai', models.IntegerField(db_column='IDPegawai', primary_key=True, serialize=False)),
                ('nip', models.CharField(blank=True, db_column='NIP', max_length=18, null=True)),
                ('nipbaru', models.CharField(blank=True, db_column='NIPBaru', max_length=18, null=True)),
                ('namalengkap', models.CharField(blank=True, db_column='NamaLengkap', max_length=8000, null=True)),
                ('kodekelamin', models.CharField(db_column='KodeKelamin', max_length=1)),
                ('kodegolongan', models.CharField(blank=True, db_column='KodeGolongan', max_length=5, null=True)),
                ('kodegolonganruang', models.CharField(blank=True, db_column='KodeGolonganRuang', max_length=5, null=True)),
                ('tmtpangkat', models.DateTimeField(blank=True, db_column='TMTPangkat', null=True)),
                ('jenjangjabatan', models.CharField(blank=True, db_column='JenjangJabatan', max_length=50, null=True)),
                ('jabatan', models.CharField(blank=True, db_column='Jabatan', max_length=255, null=True)),
                ('tmtjabatan', models.DateTimeField(blank=True, db_column='TMTJabatan', null=True)),
                ('singkatanjenjang', models.CharField(blank=True, db_column='SingkatanJenjang', max_length=5, null=True)),
                ('pendidikan', models.CharField(blank=True, db_column='Pendidikan', max_length=50, null=True)),
                ('jurusan', models.CharField(db_column='Jurusan', max_length=250)),
                ('namalembagapendidikan', models.CharField(db_column='NamaLembagaPendidikan', max_length=100)),
                ('tanggallulus', models.DateField(blank=True, db_column='TanggalLulus', null=True)),
                ('namaprogramstudi', models.CharField(blank=True, db_column='NamaProgramStudi', max_length=255, null=True)),
                ('namaprogramstudiluarnegeri', models.CharField(blank=True, db_column='NamaProgramStudiLuarNegeri', max_length=255, null=True)),
                ('idjabatan', models.IntegerField(blank=True, db_column='IDJabatan', null=True)),
                ('idorganisasi', models.IntegerField(blank=True, db_column='IDOrganisasi', null=True)),
                ('kodeorganisasi', models.CharField(blank=True, db_column='KodeOrganisasi', max_length=20, null=True)),
                ('esl1', models.TextField(db_column='Esl1')),
                ('esl2', models.TextField(db_column='Esl2')),
                ('esl3', models.TextField(db_column='Esl3')),
                ('esl4', models.TextField(db_column='Esl4')),
                ('esl5', models.TextField(db_column='Esl5')),
                ('kodesatker', models.CharField(blank=True, db_column='KodeSatker', max_length=6, null=True)),
                ('rangeusia', models.CharField(db_column='RangeUsia', max_length=10)),
                ('usiatahun', models.IntegerField(blank=True, db_column='UsiaTahun', null=True)),
                ('usiabulan', models.IntegerField(blank=True, db_column='UsiaBulan', null=True)),
                ('tanggallahir', models.DateTimeField(blank=True, db_column='TanggalLahir', null=True)),
                ('tmtpensiun', models.DateTimeField(blank=True, db_column='TmtPensiun', null=True)),
                ('tahunpensiun', models.IntegerField(blank=True, db_column='TahunPensiun', null=True)),
                ('tmtkenaikanpangkatberikutnya', models.DateTimeField(blank=True, db_column='TMTKenaikanPangkatBerikutnya', null=True)),
                ('statuspegawai', models.CharField(blank=True, db_column='StatusPegawai', max_length=100, null=True)),
                ('keterangantambahan', models.CharField(db_column='KeteranganTambahan', max_length=255)),
                ('tempatlahir', models.CharField(blank=True, db_column='TempatLahir', max_length=60, null=True)),
                ('masakerjatahun', models.IntegerField(blank=True, null=True)),
                ('grading', models.IntegerField(db_column='Grading')),
                ('idrefeselon', models.IntegerField(blank=True, db_column='IDRefEselon', null=True)),
                ('idreftingkatpendidikan', models.IntegerField(blank=True, db_column='IDRefTingkatPendidikan', null=True)),
                ('tmtstatuspegawai', models.DateTimeField(blank=True, db_column='TMTStatusPegawai', null=True)),
                ('generasi', models.CharField(blank=True, db_column='Generasi', max_length=11, null=True)),
                ('jenisjabatan', models.CharField(blank=True, db_column='JenisJabatan', max_length=100, null=True)),
                ('jpm', models.FloatField(db_column='JPM')),
                ('rangejpm', models.CharField(db_column='RangeJPM', max_length=4)),
                ('tanggalac', models.DateTimeField(db_column='TanggalAC')),
                ('ckp', models.FloatField(db_column='CKP')),
                ('np', models.FloatField(db_column='NP')),
                ('nkp', models.FloatField(db_column='NKP')),
                ('ppkp', models.FloatField(db_column='PPKP')),
                ('kriterianp', models.CharField(db_column='KriteriaNP', max_length=9)),
                ('kriteriappkp', models.CharField(db_column='KriteriaPPKP', max_length=6)),
                ('tahunlulus', models.IntegerField(blank=True, db_column='TahunLulus', null=True)),
                ('lokasipendidikan', models.CharField(db_column='LokasiPendidikan', max_length=12)),
                ('jenisorganisasi', models.CharField(blank=True, db_column='JenisOrganisasi', max_length=50, null=True)),
                ('jenisijinpendidikan', models.CharField(db_column='JenisIjinPendidikan', max_length=25)),
                ('jeniskepegawaian', models.CharField(db_column='JenisKepegawaian', max_length=255)),
                ('tipeorganisasi', models.CharField(blank=True, db_column='TipeOrganisasi', max_length=255, null=True)),
                ('masakerjajabatan', models.IntegerField(blank=True, db_column='MasaKerjaJabatan', null=True)),
                ('provinsikantor', models.CharField(blank=True, db_column='ProvinsiKantor', max_length=50, null=True)),
                ('instansidpkdpb', models.CharField(blank=True, db_column='InstansiDpkDpb', max_length=255, null=True)),
                ('jeniskantor', models.CharField(blank=True, db_column='JenisKantor', max_length=50, null=True)),
                ('statuspernikahan', models.CharField(blank=True, db_column='StatusPernikahan', max_length=50, null=True)),
                ('jenjang', models.CharField(blank=True, db_column='Jenjang', max_length=50, null=True)),
                ('kotakantor', models.CharField(blank=True, db_column='KotaKantor', max_length=50, null=True)),
            ],
            options={
                'db_table': 'data_lengkap',
                'managed': False,
            },
        ),
    ]
