# Generated by Django 4.0 on 2022-09-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='media/files/pengumuman/')),
                ('deskripsi', models.TextField()),
                ('tanggalAwal', models.DateField(verbose_name='Tanggal Awal')),
                ('tanggalAkhir', models.DateField(verbose_name='Tanggal Akhir')),
                ('tanggalCreate', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(blank=True)),
            ],
            options={
                'db_table': 'web_pengumuman',
            },
        ),
    ]
